config/routes.rb
PhotographerShare::Application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  devise_for :users

  root 'page#home'

  resources :users do
    member do
      get :following, :followers
    end

    collection do
      get :search
    end
  end

  resources :photos do
    resources :comments
  end
  resources :relationships, only: [:create, :destroy]
  resources :favourites, only: [:create, :destroy]
  resources :tags, only: [:index]
  resources :recommends, only: [:index]

end

app/models/user.rb
class User < ActiveRecord::Base
  paginates_per 20
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_save :ensure_auth_token

  has_many :photos
  has_many :comments
  accepts_nested_attributes_for :photos, allow_destroy: true

  # relationship
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed

  has_many :reverse_relationships, foreign_key: "followed_id",
                                    class_name:  "Relationship",
                                    dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower

  # favourite
  has_many :favourites, dependent: :destroy
  has_many :favourite_photos, through: :favourites, source: :photo
  has_many :received_favourites, through: :photos, source: :favourites

  # counter :received_favourites_count

  def following?(other_user)
    relationships.where(followed_id: other_user.id).first
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.where(followed_id: other_user.id).first.destroy
  end

  def favourite?(photo)
    favourites.where(photo_id: photo.id).first
  end

  def favourite!(photo)
    favourites.create!(photo_id: photo.id)
  end

  def unfavourite(photo)
    favourites.where(photo_id: photo.id).first.destroy
  end

  def ensure_auth_token
    if auth_token.blank?
      self.auth_token = generate_auth_token
    end
  end

  def generate_auth_token
    loop do
      token = Devise.friendly_token
      break token unless User.where(auth_token: token).first
    end
  end

  def feed
    # This is preliminary. See "Following customers" for the full implementation.
    Photo.from_users_followed_by(self)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @tags = Tag.all
    @user = User.find(params[:id])

    if @user == current_user
      @photos = current_user.photos.all
      @fans_photos = current_user.feed
      @photo = current_user.photos.new
    else
      @photos = @user.photos.all
    end
  end

  def edit
  end

  def update
    if current_user.update_attributes user_params
      flash[:notice] = '个人资料更新成功！'
      redirect_to current_user
    else
      flash[:notice] = '个人资料更新失败！'
      redirect_to current_user
    end
  end

  def following
    @title = "你的关注"
    @user = User.find(params[:id])
    @users = @user.followed_users.page params[:page]
    render 'show_followers'
  end

  def followers
    @title = "粉丝"
    @user = User.find(params[:id])
    @users = @user.followers.page params[:page]
    render 'show_followers'
  end

  def search
    user = User.find_by(name: params[:user_name])

    if user.nil?
      flash[:noitce] = '没有找到该用户'
      redirect_to root_path
    else
      redirect_to user_path(id: user.id)
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :phone,
      photos_attributes:[:id, :_destroy])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_form.html.erb
<% unless current_user == @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_other_photo_list.html.erb
<div class="panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
          他的图片
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in">
      <div class="panel-body">
        <%= render :partial => "shared/index_photos", :locals => { photos: photos } %>
      </div>
    </div>
  </div>
</div>

app/views/users/_own_photo_list.html.erb
<!-- add button -->
<div class="col-8 col-sm-10 col-lg-3" >
  <%= form_for(photo, url: photos_path, method: "post", html: {:multipart => true}) do |f| %>
  <button class="addButton uploadButton">
    <%= f.file_field :image_uid, :onchange => 'this.form.submit()' %>
    <p>添加图片</p>
  </button>
  <% end %>
</div>

<div class="panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
          我的图片
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in">
      <div class="panel-body">
      <div class="row">
        <% photos.each do |p| %>
          <div class="col-xs-6 .col-md-12">
            <div class="onePhoto thumbnail">
              <h4>&nbsp;<span class="favouriteScore"><%= p.score %>赞</span></h4>
                <%=image_tag p.image_uid.url(:show_small_thumb) %>

              <div class="photoButtons">
                <a href="#" data-toggle="modal" data-target="#own-<%= p.id %>" data-type="edit" class="editButton"></a>
                <%= link_to '', photo_path(id: p.id), method: :delete, data: {confirm: '确定删除这张图片?'}, class: "deleteButton" %>
              </div>
            </div>
          </div>

          <!-- 模态框 -->
          <div class="modal fade" id="own-<%=p.id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" >
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                  <h4 class="modal-title" id="myModalLabel">编辑图片</h4>
                </div>
                <div class="modal-body">
                  <div><%=image_tag p.image_uid.url(:show_big_thumb) %></div>
                  <%= form_for(p, url: photo_path(photo_id: p.id), method: 'put') do |f| %>
                    <div>
                      <%= f.label '图片描述' %>
                      <%= f.text_area :description, class: "form-control" %>
                    </div>
                    <div><%= f.label '图片标签' %></div>
                    <% tags.each do |t| %>
                      <div class="col-md-4">
                        <input <%= p.tags.include?(t) ? "checked='checked'" : "unchecked" %> type="checkbox" tag_id=<%= t.id %> name = <%= "photo[tags][#{t.id}]" %> value=<%= t.name %>><%= PhotographerShare::Application.config.tags[t.name] %></input>
                      </div>
                    <% end %>
                    <div>
                      <%= f.submit "保存", class: "btn btn-default"%>
                    </div>
                </div>
                <% end %>
              </div>
            </div>
          </div>
                  <!-- < -->
        <% end %>
      </div>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
          朋友圈图片
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse">
      <div class="panel-body">
        <%= render :partial => "photos_show", :locals => { photos: @fans_photos } %>
      </div>
    </div>
  </div>
</div>

app/views/users/_photos_show.html.erb
<div class="row">
  <% photos.each do |p| %>
    <div class="col-xs-6 .col-md-6">
      <div class="onePhoto thumbnail">
        <h4><%= link_to "#{p.user.name}", user_url(id: p.user.id) %><span class="favouriteScore"><%= p.score %>赞</span></h4>
          <%=image_tag p.image_uid.url(:show_small_thumb) %>

        <div class="OtherPhotosButtons">
<!--                    <a href="#" data-toggle="modal" data-target="#fav" data-type="edit" class="favButton">赞</a> -->
        <% if user_signed_in? && current_user.following?(p.user) %>
          <% if current_user.favourite?(p) %>
            <%= render partial: 'shared/unfavourite', locals: { photo: p } %>
          <% else %>
            <%= render partial: 'shared/favourite', locals: { photo: p } %>
          <% end %>
          <a href="#" data-toggle="modal" data-target="#show-<%= p.id %>" data-type="edit" class="commentButton">评论</a>
        <% else %>
          <a href="#" data-toggle="modal" data-target="#show-<%= p.id %>" data-type="edit" class="commentButton">查看大图</a>
        <% end %>
        </div>
      </div>
    </div>

    <!-- 模态框 -->
    <div class="modal fade" id="show-<%=p.id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" >
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="myModalLabel">图片详情</h4>
          </div>
          <div class="modal-body">
            <div><%=image_tag p.image_uid.url(:show_big_thumb) %></div>
            <label>图片描述:</label>
            <% unless p.description == '' %>
              <div class="des"><%= p.description %></div>
            <% end %>
            <div></div>
            <% if user_signed_in? && current_user.following?(p.user) %>
            <% comments = p.comments.all %>
            <% unless comments.blank? %>
              <div class="comment">
                <% comments.each do |c| %>
                  <div class="oneComment">
                    <span><%= c.user.name %>说:</span>
                    <span><%= c.content %></span>
                  </div>
                <% end %>
              </div>
              <% end %>
              <%= form_for(p.comments.new, url: photo_comments_path(photo_id: p.id), method: 'post') do |f| %>
                <div>
                  <%= f.label '添加新评论' %>
                  <%= f.text_area :content, class: "form-control" %>
                </div>
                <div>
                  <%= f.submit "保存", class: "btn btn-default"%>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='smallForm'>
<%= form_for(current_user, url: user_path, html: { method: :put }) do |f| %>

  <div><%= f.label '名字' %><br />
  <%= f.text_field :name, autofocus: true, class: "form-control" %></div>

  <div><%= f.label '电话' %><br />
  <%= f.text_field :phone, autofocus: true, class: "form-control" %></div>

  <div><%= f.submit "更新", class: 'btn btn-primary' %></div>
<% end %>

<%= link_to "返回", :back %>
</div>

app/views/users/show.html.erb
<h3>个人资料</h3>
<div class="row">
  <aside class="span4">
    <table class="user_profile">
      <thead><tr><td>账号：<%=  @user.email %></td></tr></thead>
      <tbody>
        <tr>
          <td>名字：<%= @user.name == '' ? '这家伙很懒，神马都没留下' : @user.name %></td>
        </tr>
        <tr>
          <td>手机：<%= @user.phone == '' ? '这家伙很懒，神马都没留下' : @user.phone %></td>
        </tr>
        <%  if @user == current_user %>
          <tr>
            <td>登录次数：<%= @user.sign_in_count %></td>
          </tr>
          <tr>
            <td>上次登录：<%= @user.last_sign_in_at.strftime("%Y-%m-%d %H:%M") %></td>
          </tr>
        <% end %>
        <tr><td><%= render 'shared/follow_form' %></td></tr>
      </tbody>
    </table>
    <section>
        <%= render 'shared/stats' %>
    </section>
  </aside>

  <% if current_user == @user %>
    <%= render :partial => "own_photo_list", :locals => { photo: @photo, photos: @photos, fans_photos: @fans_photos, tags: @tags } %>
  <% else %>
    <%= render :partial => "other_photo_list", :locals => { photos: @photos } %>
  <% end %>
</div>

app/views/users/show_followers.html.erb
<h3><% provide(:title, @title) %></h3>
<div class="row">
  <aside class="span4">
    <section>
      <h1><%= @user.name %></h1>
      <span><%= link_to "查看我的资料", @user %></span>
      <span><b>Photographs:</b> <%= @user.photos.count %></span>
    </section>
    <section>
      <%= render 'shared/stats' %>
  </aside>
  <div class="span8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users">
        <% @users.each do |u| %>
          <li><%= link_to u.name, u %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>