config/routes.rb
PhotographerShare::Application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  devise_for :users

  root 'page#home'

  resources :users do
    member do
      get :following, :followers
    end

    collection do
      get :search
    end
  end

  resources :photos do
    resources :comments
  end
  resources :relationships, only: [:create, :destroy]
  resources :favourites, only: [:create, :destroy]
  resources :tags, only: [:index]
  resources :recommends, only: [:index]

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :photo
  belongs_to :user
end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
  belongs_to :user
  belongs_to :photo

  validates :user_id, :photo_id, presence: true

  after_create :increment_photo_score
  after_destroy :decrement_photo_score

  def increment_photo_score
    photo.increment(:score)
    photo.save
  end

  def decrement_photo_score
    photo.decrement(:score)
    photo.save
  end

  # after_create do
  #   photo.user.received_favourites_count.increment
  # end

  # after_destroy do
  #   photo.user.received_favourites_count.decrement
  # end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :image_uid, PhotoUploader

  has_and_belongs_to_many :tags
  belongs_to :user
  has_many :comments
  has_many :favourites, dependent: :destroy
  has_many :favourited_by_users, through: :favourites, source: :user

  def self.from_users_followed_by(user)
    followed_user_ids = "SELECT followed_id FROM relationships
                         WHERE follower_id = :user_id"
    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id",
          user_id: user.id)
  end

  # def self.increment_score
  #   increment(:score)
  # end

  # def self.decrement_score
  #   decrement(:score)
  # end

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name:"User"
  belongs_to :followed, class_name:"User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :photos
end

app/models/user.rb
class User < ActiveRecord::Base
  paginates_per 20
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_save :ensure_auth_token

  has_many :photos
  has_many :comments
  accepts_nested_attributes_for :photos, allow_destroy: true

  # relationship
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed

  has_many :reverse_relationships, foreign_key: "followed_id",
                                    class_name:  "Relationship",
                                    dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower

  # favourite
  has_many :favourites, dependent: :destroy
  has_many :favourite_photos, through: :favourites, source: :photo
  has_many :received_favourites, through: :photos, source: :favourites

  # counter :received_favourites_count

  def following?(other_user)
    relationships.where(followed_id: other_user.id).first
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.where(followed_id: other_user.id).first.destroy
  end

  def favourite?(photo)
    favourites.where(photo_id: photo.id).first
  end

  def favourite!(photo)
    favourites.create!(photo_id: photo.id)
  end

  def unfavourite(photo)
    favourites.where(photo_id: photo.id).first.destroy
  end

  def ensure_auth_token
    if auth_token.blank?
      self.auth_token = generate_auth_token
    end
  end

  def generate_auth_token
    loop do
      token = Devise.friendly_token
      break token unless User.where(auth_token: token).first
    end
  end

  def feed
    # This is preliminary. See "Following customers" for the full implementation.
    Photo.from_users_followed_by(self)
  end

end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
    @last_updated_photos = Photo.order('updated_at DESC').limit(10)
    @tags = Tag.all

  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!

  def create
    photo = current_user.photos.new photo_params

    if photo.save
      flash[:notice] = '图片创建成功'
    else
      flash[:error] = '图片创建失败'
    end

    redirect_to current_user
  end

  def update
    photo = current_user.photos.find(params[:photo_id])

    if photo.update_attributes photo_params
      #judge if user check fix_services
      if params[:photo][:tags]
        photo.tags.destroy_all
        params[:photo][:tags].each_key do |pt|
          photo.tags.concat(Tag.find(pt))
        end
      end
      flash[:notice] = '图片更新成功'
    else
      flash[:error] = '图片更新失败'
    end

    redirect_to current_user
  end

  def destroy
    photo = current_user.photos.find(params[:id])

    if photo.destroy
      flash[:notice] = '图片删除成功'
    else
      flash[:error] = '图片删除失败'
    end

    redirect_to current_user
  end

  private
  def photo_params
    params.require(:photo).permit(:image_uid, :description)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    # binding.pry
    @tag = Tag.where(name: params[:tag_name]).first
    if @tag.nil?
      @tag_name = params[:name].to_s
    else
      @special_tag_photos = @tag.photos.order('updated_at DESC')
    end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @tags = Tag.all
    @user = User.find(params[:id])

    if @user == current_user
      @photos = current_user.photos.all
      @fans_photos = current_user.feed
      @photo = current_user.photos.new
    else
      @photos = @user.photos.all
    end
  end

  def edit
  end

  def update
    if current_user.update_attributes user_params
      flash[:notice] = '个人资料更新成功！'
      redirect_to current_user
    else
      flash[:notice] = '个人资料更新失败！'
      redirect_to current_user
    end
  end

  def following
    @title = "你的关注"
    @user = User.find(params[:id])
    @users = @user.followed_users.page params[:page]
    render 'show_followers'
  end

  def followers
    @title = "粉丝"
    @user = User.find(params[:id])
    @users = @user.followers.page params[:page]
    render 'show_followers'
  end

  def search
    user = User.find_by(name: params[:user_name])

    if user.nil?
      flash[:noitce] = '没有找到该用户'
      redirect_to root_path
    else
      redirect_to user_path(id: user.id)
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :phone,
      photos_attributes:[:id, :_destroy])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
      base_title = "Huo photo share"
      if page_title.empty?
        base_title
      else
        "#{base_title} | #{page_title}"
      end
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/recommends_helper.rb
module RecommendsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://huoshiqiu.cc/">made by Jed</a>
  </small>
  <nav>
    <ul>

    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "图缤纷", root_path, class: "navbar-brand", id: 'logo' %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li><%= link_to "推荐", recommends_path %></li>
      <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">我的账号<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "个人资料", user_path(current_user.id) %></li>
            <li><%= link_to "修改密码", edit_user_registration_path %></li>
            <li><%= link_to "设置", edit_user_path(id: current_user.id) %></li>
            <li class="divider"></li>
            <li><%= link_to "登出", destroy_user_session_path, method: "DELETE" %></li>
          </ul>
        </li>
      <% else %>
      <li><%= link_to "登录", new_user_session_path %></li>
      <% end %>
    </ul>
<!--     <form class="navbar-form navbar-left" role="search">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="输入用户或标签按回车">
      </div>
    </form> -->
    <%= form_tag(search_users_path, method: 'get', class: 'navbar-form navbar-left', role: 'search') do %>
      <div class="form-group">
        <input type="text" name='user_name' class="form-control" onchange='this.form.submit()' placeholder="输入用户名字按回车">
      </div>
    <% end %>
  </div><!-- /.navbar-collapse -->
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all",
                                            "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "alert alert-info") %>
    <% end %>
    <%= yield %>
    </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/page/home.html.erb
<h3>最近更新图片：</h3>
<div class="myPhotoCarousel">
  <% @last_updated_photos.each do |photo| %>
    <div>
      <%= image_tag photo.image_uid.url(:show_small_thumb) %>
    </div>
  <% end %>
</div>

<div class='row'>
  <div class="col-lg-6">
    <div class="input-group">
      <div class="input-group-btn">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">已有标签 <span class="caret"></span></button>
        <ul class="dropdown-menu">
        <% @tags.each do |tag| %>
          <li><a href="<%= tags_path(tag_name: tag.name) %>"><%= PhotographerShare::Application.config.tags[tag.name] %></a></li>
        <% end %>
        </ul>
      </div><!-- /btn-group -->
      <%= form_tag(tags_path, method: 'get') do %>
        <input type="text" name='tag_name' class="form-control" onchange='this.form.submit()' placeholder="输入你喜爱的标签按回车">
      <% end %>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
</div>
<% @tags.each do |tag| %>
  <% unless tag.photos.blank? %>
    <h4><%= link_to "#{PhotographerShare::Application.config.tags[tag.name]}", tags_path(tag_name: tag.name)%></h4>
      <%= render :partial => "shared/index_photos", :locals => {
        photos: tag.photos.order('updated_at DESC').limit(3) } %>
  <% end %>
<% end %>

app/views/shared/_favourite.html.erb
<%= form_for(current_user.favourites.build(photo_id: photo.id),
             remote: true) do |f| %>
  <div><%= f.hidden_field :photo_id %></div>
  <%= f.submit "赞", class: "btn btn-success", id: 'favourite' %>
<% end %>

app/views/shared/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id),
             remote: true) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "关注", class: "btn btn-success" %>
<% end %>

app/views/shared/_follow_form.html.erb
<% unless current_user == @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'shared/unfollow' %>
  <% else %>
    <%= render 'shared/follow' %>
  <% end %>
  </div>
<% end %>

app/views/shared/_index_photos.html.erb
<div class="row">
  <% photos.each do |p| %>
    <div class="col-xs-4 .col-md-6">
      <div class="onePhoto thumbnail">
        <h4><%= link_to "#{p.user.name}", user_url(id: p.user.id) %><span class="favouriteScore"><%= p.score %>赞</span></h4>
          <%=image_tag p.image_uid.url(:show_small_thumb) %>

        <div class="OtherPhotosButtons">
<!--                    <a href="#" data-toggle="modal" data-target="#fav" data-type="edit" class="favButton">赞</a> -->
        <% if user_signed_in? && current_user.following?(p.user) %>
          <% if current_user.favourite?(p) %>
            <%= render partial: 'shared/unfavourite', locals: { photo: p } %>
          <% else %>
            <%= render partial: 'shared/favourite', locals: { photo: p } %>
          <% end %>
          <a href="#" data-toggle="modal" data-target="#show-<%= p.id %>" data-type="edit" class="commentButton">评论</a>
        <% else %>
          <a href="#" data-toggle="modal" data-target="#show-<%= p.id %>" data-type="edit" class="commentButton">查看大图</a>
        <% end %>
        </div>
      </div>
    </div>

    <!-- 模态框 -->
    <div class="modal fade" id="show-<%=p.id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" >
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="myModalLabel">图片详情</h4>
          </div>
          <div class="modal-body">
            <div><%=image_tag p.image_uid.url(:show_big_thumb) %></div>
            <label>图片描述:</label>
            <% unless p.description == '' %>
              <div class="des"><%= p.description %></div>
            <% end %>
            <div></div>
            <% if user_signed_in? && current_user.following?(p.user) %>
            <% comments = p.comments.all %>
            <% unless comments.blank? %>
              <div class="comment">
                <% comments.each do |c| %>
                  <div class="oneComment">
                    <span><%= c.user.name %>说:</span>
                    <span><%= c.content %></span>
                  </div>
                <% end %>
              </div>
              <% end %>
              <%= form_for(p.comments.new, url: photo_comments_path(photo_id: p.id), method: 'post') do |f| %>
                <div>
                  <%= f.label '添加新评论' %>
                  <%= f.text_area :content, class: "form-control" %>
                </div>
                <div>
                  <%= f.submit "保存", class: "btn btn-default"%>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    关注
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    粉丝
  </a>
</div>

app/views/shared/_unfavourite.html.erb
<%= form_for(current_user.favourites.find_by(photo_id: photo.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "取消赞", class: "btn btn-danger", id: 'unfavourite' %>
<% end %>

app/views/shared/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "取消关注", class: "btn btn-danger" %>
<% end %>